### ISSUE TITLE
Incorporate SCOUT_LOG_LEVEL

### ISSUE THREAD

**Issue by shawnbro** [scoutapp/scout_apm_elixir#20]
Would it be possible to incorporate using the `SCOUT_LOG_LEVEL` constant - the lib right now floods my production logs with `info` logs that aren't necessary.

**Comment by itsderek23** [comment]
@shawnbro - Agree that the logging output is too noisy. 

@cschneid - ideas to share? It's an issue in development as well as the messages interrupt `iex` sessions.

**Comment by cschneid** [comment]
Logging with Elixir is something I haven't fully groked the intricacies of yet.  @shawnbro I assume you're using the default console output with the logger? Or are you using an alternate backend (like `logger_file_backend` or similar)

In the ruby agent, we use our own `Logger.new()` instance which we can set the level of independently based on the `SCOUT_LOG_LEVEL` setting. But Elixir's built-in `Logger` application is effectively a singleton, which makes it difficult to configure for just one section of the overall running system.

Options I see:

1. Write our own logging infrastructure, entirely bypassing the builtin `Logger`. This seems iffy, since we'd give up all the nice backends that exist
2. Wrap the builtin `Logger` with something like `ScoutApm.Logger.info`, which simply checks the `SCOUT_LOG_LEVEL` constant, and either passes through or not.  This would be straightforward, but feels odd.
3. Provide a Logger filter class doing similar things to option 2

And a longer-term 4th option is to submit patches to Elixir's logging system to let it handle this kind of use case.

**Comment by itsderek23** [comment]
For production, couldn't we just change the log level of the recurring payload-related messages to `DEBUG`?

**Comment by cschneid** [comment]
Yeah, another option would be to just move most log messages in the agent to debug level.

**Comment by itsderek23** [comment]
@shawnbro - we've released scout_apm 0.2.12. This silences the log at the `INFO` level during the regular reporting cycles.

**Comment by shawnbro** [comment]
awesome will update. thank you @itsderek23 @cschneid
