### ISSUE TITLE
Support non-import use

### ISSUE THREAD

**Issue by jstr** [scoutapp/scout_apm_elixir#66]
The recent releases of `scout_apm` deprecate the `use` method and require the use of `import ScoutApm.Tracing`.

This poses challenges for interoperability with some other packages, e.g. https://github.com/Nebo15/sage, and also unnecessary pollutes the function space by importing `transaction`, etc.

Ideally `scout_apm` should be useable without `import`ing its functions and creating potential conflicts.

**Comment by cschneid** [comment]
@jstr - thank you for the report. The `transaction` and `timing` "functions" are actually macros, so will require some sort of "import" to work.

Instead of `import`, which brings names into the module's namespace, can you try `require ScoutApm.Tracing`, which shouldn't affect namespace, but does enable macros from the Tracing package. After that you should be able to refer to them by their full name `ScoutApm.Tracing.transaction(....) do ... end`

In addition, you can scope `import` and `require` calls [inside individual functions](https://elixir-lang.org/getting-started/alias-require-and-import.html#require), which may be another way to minimize name leakage.

**Comment by jstr** [comment]
Thanks @cschneid, this what I ended up doing. I do think the documentation could be clearer about usage in this respect.

**Comment by mitchellhenke** [comment]
Closing this issue as I've added a note about collisions and a link to the Elixir documentation on it.  Thanks for opening the issue 🙂
