### ISSUE TITLE
ScoutAPM.PersistentHistogram Terminating`

### ISSUE THREAD

**Issue by shawnbro** [scoutapp/scout_apm_elixir#7]
i just deployed the scout elixir APM, and getting the following error:
![screen shot 2017-04-26 at 1 46 52 pm](https://cloud.githubusercontent.com/assets/6208719/25456114/d60d3642-2a86-11e7-9ffd-f64bafdf3d2b.png)

reports seem to be going through correctly.  Any help with this bug?

also nothing is showing up in the scout console.

**Comment by cschneid** [comment]
I couldn't get this to reproduce locally, but I'm pretty sure it was a race condition when we stored histograms vs when we *used* histograms in recording a trace. I reversed the order, made recording them synchronous, and added safe return values of `:error` instead of exceptions.

`0.2.7` should have this fixed.
